name: Build touchHLE

on:
  push:
    branches: [ "trunk" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-win:
    runs-on: windows-2022
    steps:
    - name: Checkout touchHLE
      shell: bash
      run: |
        git config --global core.autocrlf false
        mkdir -p "$GITHUB_WORKSPACE"
        git clone "https://github.com/${{ github.repository }}.git" "$GITHUB_WORKSPACE"
        cd "$GITHUB_WORKSPACE"
        git fetch origin "$GITHUB_REF"
        git checkout "$GITHUB_SHA"
    - name: Appliquer les patchs
      shell: bash
      run: |
        shopt -s nullglob
        for p in *.patch; do
          echo "== $p"
          git apply --ignore-whitespace "$p"
        done
    - name: Get Submodules
      run: git submodule update --init
    - name: Try to get cached copy of Boost
      id: cache-boost
      uses: actions/cache@v4
      with:
        path: vendor\boost
        key: boost_1_81_0
    - if: ${{ steps.cache-boost.outputs.cache-hit != 'true' }}
      name: Download Boost
      run: curl -L -o boost_1_81_0.7z "https://archives.boost.io/release/1.81.0/source/boost_1_81_0.7z"
    - if: ${{ steps.cache-boost.outputs.cache-hit != 'true' }}
      name: Extract Boost
      run: 7z -ovendor x boost_1_81_0.7z > $null && ren vendor\boost_1_81_0 boost
    - name: Try to get cached copy of cmake
      id: cache-cmake
      uses: actions/cache@v4
      with:
        path: vendor/cmake
        key: cmake_3_31_6_windows
    - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
      name: Download Cmake
      run: curl -L -O "https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6-windows-x86_64.zip"
    - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
      name: Extract Cmake
      run: 7z -ovendor x "cmake-3.31.6-windows-x86_64.zip" > $null && ren vendor\cmake-3.31.6-windows-x86_64 cmake
    - name: Build
      run: cargo build --release
      env:
        CMAKE: ${{ github.workspace }}\vendor\cmake\bin\cmake
    - name: Create bundle
      shell: bash
      run: cd dev-scripts && ./make-windows-bundle.sh ../target/release/touchHLE.exe && mv touchHLE_windows_bundle/ ..
    - uses: actions/upload-artifact@v4
      with:
        name: touchHLE_Windows_x86_64
        path: touchHLE_windows_bundle/
